Feature migration landing
TeamBookTez/nextjs-book-stairs pull request #18
Opened 2022-04-29 09:12 UTC by q-bit-junior

## 📌 나 이런 거 했어요
- 랜딩 페이지(반응형 모바일 랜딩페이지) 마이그레이션을 완료했습니다!

<br />

## 📌 나 이런 거 알게 되었어요
- 우선 svg 파일을 이전처럼 컴포넌트로 사용하기 위해서 webpack을 설치하고 next.config.js 를 수정하였습니다.  
- 이 방식으로 이용하기 위해서는 ReactComponent 로 export 해주었던 부분을 모두 default 로 바꾸어 주어야 했습니다. 따라서 asset.d.ts 파일에 있는 svg에 관한 모듈 선언은 없애도 될 것 같습니다만 우선 주석처리를 해놓았습니다.
- `useNavigation` 을 이용했던 부분을 `useRouter`를 이용하여 router.push("/main")과 같은 방식으로 이용했습니다. 이 때, 데이터를 전달하기 위해서 `{ state: "rightpath" }` 를 함께 navigate 했던 부분을 router.push 에서는 query 객체 안에 넣어주었습니다. (`{ query : {state: "rightpath" }}`) 나중에 회원가입 페이지에서 받아서 쓸 때 잘 넘어오는지 확인은 해봐야할 것 같아요.
- styled-component를 이용할 때는 background-image 를 위해 `url(${이미지컴포넌트})` 와 같은 방식으로 했었는데 emotion에서는 되지 않았습니다. 따라서 props로 넘겨주는 방식을 택했고 `url(${props => props.landingImg.src})` 와 같이 뒤에 `.src` 를 붙여줘야 했습니다.

<br />

## 📌 나 이런 거 궁금해요
- Image를 props로 넘겨줄 때 interface를 만들었는데 `ImgHTMLAttributes<string>` 로 하니까 문제가 없었습니다. 그렇지만 type 지정을 잘 해준 것인지 확신이 서지는 않는군요.

2022-04-30 07:36 UTC, joohaem approved these changes
최고의 퀄리티🔥🔥 고생 많으셨습니다 !!!~

2022-04-30 07:36 UTC, joohaem commented on src/components/landing/LandingFive.tsx
> +`;
`img` 태그 대신에, Next JS 에서 제공하는 `Image` 태그를 사용해보는 것 어떨까 합니답!

2022-04-30 07:36 UTC, joohaem commented on next.config.js
> +  },
고생하셨습니다👍👍❤😚 신기하네욥

2022-04-30 07:36 UTC, joohaem commented on package.json
> +    "@svgr/webpack": "^6.2.1",
무엇이냐 너란 녀석,!

2022-04-30 07:36 UTC, joohaem commented on src/components/landing/LandingHeader.tsx
> +          <StBtnSignup onClick={() => router.push("/signup", { query: { state: "rightpath" } })}>회원가입</StBtnSignup>
오 신기하네요!!!!👍👍

근데 하나 고민점이 사실
`rightpath` state 를 넘겨줘야 하는 고민이 있어요!!

로그인 페이지나, 랜딩 페이지의 회원가입 버튼을 통해서만 접근할 수 있도록 구현한건데,
꼭 필요할까에 대한 확신이 서지 않는 상태입니다😥😥
어떻게 생각하시나요??!

2022-04-30 07:36 UTC, joohaem commented on src/components/landing/LandingThree.tsx
> +`;
`오 이렇게 스타일 설정 가능한가요??!
여러 제약 사항들이 있어서 div로 wrapping 하여 스타일링 하는 방식을 주로 사용한다고 알고 있어서요!`

이하동문입니다!

2022-04-30 07:36 UTC, joohaem commented on src/components/landing/LandingOne.tsx
> +`;
오 이렇게 스타일 설정 가능한가요??!
여러 제약 사항들이 있어서 div로 wrapping 하여 스타일링 하는 방식을 주로 사용한다고 알고 있어서요!

2022-04-30 07:36 UTC, joohaem commented on src/components/landing/LandingCard.tsx
>  }
Mobile 과 겹치는 props 인 것 같은데, 
`types`/`landing.ts` 파일에 모아두는 것은 어떨까요??

props interface라 따로 선언하는 것도 좋을 것 같고,
의미가 통일되므로 그대로 여기서 export 하는 것도 괜찮을 것 같긴 합니다!!

어떻게 생각하시나요??~

2022-04-30 07:36 UTC, joohaem commented on src/components/landing/MobileLandingOne.tsx
> +  }
충분히 적절한 코드라고 생각하지만, 통일성을 위해 `useMediaQuery` 함수를 사용하는 건 어떻다고 생각하시나욥??!?

2022-04-30 07:36 UTC, joohaem commented on src/components/landing/MobileLandingOne.tsx
> +    <StWrapper landingImg={ImgLandingMobileBanner} mobileLandingImg={ImgLandingTabletBanner}>
신기하네요 !!!!~ 찾느라 고생하셨습니다🔥🔥🔥👍

하나 궁금한 점은, 스타일링 prop을 넘겨줄 떄, 모두 소문자로 명명해야 하는 warning은 따로 뜨지 않던가요??!
React JS 에서는 떴던 것 같아서
`landingimg`, `mobilelandingimg` 이런 식으로 명명했던 것 같아서요!

2022-04-30 07:37 UTC, joohaem commented on src/util/hooks/useMediaQuery.tsx
> +  return <React.Fragment>{isMobileScreen && children}</React.Fragment>;
```suggestion
  return <>{isMobileScreen && children}</>;
```

2022-04-30 07:38 UTC, joohaem commented on src/util/hooks/useMediaQuery.tsx
> +  return <React.Fragment>{isDesktopScreen && children}</React.Fragment>;
```suggestion
  return <>{isDesktopScreen && children}</>;
```

2022-04-30 07:39 UTC, joohaem commented on src/components/landing/MobileLandingOne.tsx
> +    <StWrapper landingImg={ImgLandingMobileBanner} mobileLandingImg={ImgLandingTabletBanner}>
```suggestion
    <StWrapper landingimg={ImgLandingMobileBanner} mobilelandingimg={ImgLandingTabletBanner}>
```

2022-04-30 07:43 UTC, joohaem commented on src/pages/index.tsx
> +  }, [isLogin]);
```suggestion
  useEffect(() => {
    setIsLogin(isLogin);
    if (isLogin) router.push("/main");
  }, [isLogin]);
```

2022-04-30 07:45 UTC, joohaem approved these changes

2022-05-01 06:58 UTC, q-bit-junior commented on src/pages/index.tsx
> +  }, [isLogin]);
훨신 간결하고 좋은 표현이군요!

2022-05-01 07:00 UTC, q-bit-junior commented on src/pages/index.tsx
> +            <MobileLandingFooter />
저도 같은 생각입니다! 순서는 파악 가능하지만 어느 부분을 의미하는지 잘 모르겠더라구요!

2022-05-01 07:01 UTC, q-bit-junior commented on src/pages/index.tsx
> +                <LandingFive />
랜딩페이지와 모바일 렌딩 페이지 one~five 까지 적절한 네이밍을 고려해보겠습니다!

2022-05-01 07:02 UTC, q-bit-junior commented on src/components/landing/LandingOne.tsx
> +`;
제약사항이라는게 어떤 부분인지는 모르겠지만! 랜딩페이지에서는 충분히 저 방식으로 가능했습니다! 만약에
제약사항이 있게 된다면 wrapper로 감싸는 방식으로 통일성있게 가져가보는 것도 좋을 것 같네요!

2022-05-01 07:03 UTC, q-bit-junior commented on src/components/landing/MobileLandingOne.tsx
> +  }
네! 적용해서 수정해보도록 하겠습니다!

2022-05-01 07:05 UTC, q-bit-junior commented on src/components/landing/LandingCard.tsx
>  }
겹치는 부분을 고려하지 못했는데 말씀해주신 것처럼 `types`/`landing.ts` 파일에 모아두는 것이 더 좋을 것 같다는 생각입니다.
추후에 랜딩페이지를 수정하게 된다거나 추가하는 일이 있다면 확장성을 위해서 만들어 두는 방법도 좋은 것 같습니다!

2022-05-01 07:07 UTC, q-bit-junior commented on src/components/landing/MobileLandingOne.tsx
> +    <StWrapper landingImg={ImgLandingMobileBanner} mobileLandingImg={ImgLandingTabletBanner}>
네! warning을 모두 없애기 위해서 확인했는데 소문자로 명명해야 하는 경고 문구는 뜨지 않았습니다!
문제가 없어서 가독성을 위해 카멜케이스를 썼는데, 소문자로 변경하는 것이 좋을까요?

2022-05-02 14:56 UTC, joohaem commented on src/components/landing/MobileLandingOne.tsx
> +    <StWrapper landingImg={ImgLandingMobileBanner} mobileLandingImg={ImgLandingTabletBanner}>
따로 경고 문구가 뜨지 않았다면 괜찮을지도.!~?

2022-05-02 15:26 UTC, joohaem requested changes
제 파트 마이그레이션 하다보니 말 할 게 한 두가지 추가되네요,,,.^^하하하

2022-05-02 15:26 UTC, joohaem commented on src/components/landing/LandingOne.tsx
> +          <Link href="/main">
```suggestion
          <Link href="/main" passHref>
```

맞는지는 모르겠지만 `passHref` 넣어주기?!
[참고 블로그](https://f-dever-error-log.tistory.com/56)

2022-05-02 15:26 UTC, joohaem commented on src/components/landing/LandingFooter.tsx
> +        <Link href="/main">
```suggestion
          <Link href="/main" passHref>
```

맞는지는 모르겠지만 `passHref` 넣어주기?!
[참고 블로그](https://f-dever-error-log.tistory.com/56)

2022-05-02 16:06 UTC, q-bit-junior commented on src/components/landing/MobileLandingOne.tsx
> +    <StWrapper landingImg={ImgLandingMobileBanner} mobileLandingImg={ImgLandingTabletBanner}>
아하! 네 시도해보겠습니다!

2022-05-02 16:10 UTC, q-bit-junior commented on src/components/landing/LandingOne.tsx
> +          <Link href="/main">
첨부해 주신 참고 블로그에 따르면 
passHref 를 넣지 않을 경우(`<Link>` 의 자식으로 커스텀 컴포넌트(`styled-component` 등)을 사용할때)
하위 컴포넌트로 href 속성이 전달되지 않는다는 거군요!

즉 passHref를 넣는 이유는 a 태그에 href가 빠져있는 것을 방지하기 위함이고,
UX, SEO 에 좋지 않은 영향을 주는 것을 막기 위함이네요!

2022-05-02 16:10 UTC, q-bit-junior commented on src/components/landing/LandingFooter.tsx
> +        <Link href="/main">
수정후에 다시 pr을 날리도록 하겠습니다!

2022-05-12 11:19 UTC, soryeongk approved these changes
피드백까지 다 반영해뒀었네...!!! 넘 고생했어 고마오!

2022-05-12 11:19 UTC, soryeongk commented on src/components/landing/LandingHeader.tsx
> +          <StBtnSignup onClick={() => router.push("/signup", { query: { state: "rightpath" } })}>회원가입</StBtnSignup>
이전 방문 기록이 일부 목록 중 하나일 때만 회원가입 페이지를 정상적으로 렌딩한다고 생각하면 회원가입 페이지의 렌더링 때 `window.history.state.prevUrl` 하는 방법도 있고, 아마 useRouter에서도 그 history를 저장하고 있을 것 같아욤!

그런데 회원가입에 접근하지 못하게 하려던 이유가 회원가입 url이 signup/2 signup/3 signup/4 등으로 나눠져있었기 때문이었던 것 같은데, 이번 리팩토링에서 url을 signup 하나만 사용하면서 컴포넌트만 변하도록 변경하고 있습니다! 전부 다 중복되는 것들이었어서! 그렇게 변경된다면 회원가입에 접근하면 안되는 경우는 이미 회원인 경우(로그인 된 경우)만 있을 것 같아요

state를 넘기지 말고 회원가입 페이지 초장에 로그인 여부를 판별하는 것만 추가하면 어떨까요?

2022-05-12 11:19 UTC, soryeongk commented on src/components/landing/LandingOne.tsx
> +          <Link href="/main">
멋져용

2022-05-12 11:19 UTC, soryeongk commented on src/components/landing/LandingOne.tsx
> +`;
나는 계속 규민이가 사용한 방식으로 했었움! 제약사항이 몰까!?!

2022-05-12 11:19 UTC, soryeongk commented on src/components/landing/MobileLandingOne.tsx
> +    <StWrapper landingImg={ImgLandingMobileBanner} mobileLandingImg={ImgLandingTabletBanner}>
음 그 워닝도 처음에는 뜨지 않다가 dev tools가 돌아다니다 발견해서 띄우고 있던 것 같은데, 만약 워닝뜨면 그때는 무조건 그렇게 하고 지금은 일단 두까? 워닝이 뜨는 것은 알지만, 사실 아직도 왜 그걸 허용하지 않는지는 납득이 안돼.. styled-component github issue에 있을지도 모르겠지만,, 찾아보기 구찮!

2022-05-12 11:19 UTC, soryeongk commented on src/components/landing/MobileLandingOne.tsx
> +  }
useMediaQuery로 통일 좋아유

2022-05-12 13:34 UTC, merged